// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYauwBSjKF4ON0-qx6bCk5ZAdKRFZwCsM',
    appId: '1:148972554874:web:814d6e8ac8da8c66e249c3',
    messagingSenderId: '148972554874',
    projectId: 'study-ai-1ab16',
    authDomain: 'study-ai-1ab16.firebaseapp.com',
    storageBucket: 'study-ai-1ab16.firebasestorage.app',
    measurementId: 'G-L7EXK5CCZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuuzL0xri0L9IdPZxJQWSWBjO5kxThfrQ',
    appId: '1:148972554874:android:03793d36bf46b489e249c3',
    messagingSenderId: '148972554874',
    projectId: 'study-ai-1ab16',
    storageBucket: 'study-ai-1ab16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdx1W7sdPF4AC2Ptkp3Knw5yg4SmP74vs',
    appId: '1:148972554874:ios:8af20b78bbbec394e249c3',
    messagingSenderId: '148972554874',
    projectId: 'study-ai-1ab16',
    storageBucket: 'study-ai-1ab16.firebasestorage.app',
    iosClientId: '148972554874-lekn83s7cqvqu9itb6tmil7dsib33k27.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdx1W7sdPF4AC2Ptkp3Knw5yg4SmP74vs',
    appId: '1:148972554874:ios:8af20b78bbbec394e249c3',
    messagingSenderId: '148972554874',
    projectId: 'study-ai-1ab16',
    storageBucket: 'study-ai-1ab16.firebasestorage.app',
    iosClientId: '148972554874-lekn83s7cqvqu9itb6tmil7dsib33k27.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYauwBSjKF4ON0-qx6bCk5ZAdKRFZwCsM',
    appId: '1:148972554874:web:557e81e052ea7bede249c3',
    messagingSenderId: '148972554874',
    projectId: 'study-ai-1ab16',
    authDomain: 'study-ai-1ab16.firebaseapp.com',
    storageBucket: 'study-ai-1ab16.firebasestorage.app',
    measurementId: 'G-EFW59FPCZG',
  );
}
